services:
  mongo:
    image: mongo:latest
    container_name: mongodb_catalog
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: cloud-product-catalog
    restart: unless-stopped
