name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      localstack:
        image: localstack/localstack
        ports:
          - 4566:4566
      mongo:
        image: mongo:latest
        
        ports:
          - "27017:27017"
        env:
          MONGO_INITDB_DATABASE: cloud-product-catalog        
    env:
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_REGION: us-east-1
      AWS_ENDPOINT_URL: http://localhost:4566

    steps:
      - name: Checkout do c칩digo
        uses: actions/checkout@v4

      - name: Configurar JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: An치lise est치tica do c칩digo com checkstyle
        run: mvn checkstyle:check
      
      - name: Configurar AWS CLI para LocalStack
        run: aws configure set aws_access_key_id test && aws configure set aws_secret_access_key test

      - name: Construir e rodar testes
        run: mvn clean install        

      - name: Armazenar resultados dos testes em caso de falha
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: target/surefire-reports/